echo pozor prepise soubory, v pripade genervani noveho vzoru odstrante radek goto :end
goto :end
copy /y _vzor.jpg vodni_prvky-akumulace_balvanu.jpg
copy /y _vzor.jpg vodni_prvky-akumulace_sedimentu.jpg
copy /y _vzor.jpg vodni_prvky-balvanity_skluz.jpg
copy /y _vzor.jpg cesty_apod-cesta_brod.jpg
copy /y _vzor.jpg eroze-brehova_natrz.jpg
copy /y _vzor.jpg cesty_apod-cesta.jpg
copy /y _vzor.jpg cesty_apod-cesta_stara.jpg
copy /y _vzor.jpg eroze-eroze_plosna.jpg
copy /y _vzor.jpg eroze-eroze_struzkova.jpg
copy /y _vzor.jpg odvodneni-horska_vpust.jpg
copy /y _vzor.jpg ostatni-jine.jpg
copy /y _vzor.jpg cesty_apod-cesta_lavka.jpg
copy /y _vzor.jpg ostatni-lom.jpg
copy /y _vzor.jpg ostatni-manipulacni_prostor.jpg
copy /y _vzor.jpg vodni_prvky-mokrad_mapovany.jpg
copy /y _vzor.jpg cesty_apod-cesta_most.jpg
copy /y _vzor.jpg eroze-mura.jpg
copy /y _vzor.jpg vodni_prvky-nahon.jpg
copy /y _vzor.jpg cesty_apod-cesta_most_neexistujici.jpg
copy /y _vzor.jpg odvodneni-odvodnovaci_strouha.jpg
copy /y _vzor.jpg vodni_prvky-opevneni_brehu.jpg
copy /y _vzor.jpg ostatni-paseka.jpg
copy /y _vzor.jpg vodni_prvky-plocha_pro_rozliv.jpg
copy /y _vzor.jpg vodni_prvky-poldr.jpg
copy /y _vzor.jpg eroze-potvrzena_trasa_bleskove_povodne.jpg
copy /y _vzor.jpg vodni_prvky-prah_toku.jpg
copy /y _vzor.jpg vodni_prvky-pramen.jpg
copy /y _vzor.jpg vodni_prvky-prameniste.jpg
copy /y _vzor.jpg cesty_apod-propustek.jpg
copy /y _vzor.jpg vodni_prvky-prehrazka.jpg
copy /y _vzor.jpg vodni_prvky-prehrazka_v_prikopu.jpg
copy /y _vzor.jpg ostatni-priblizovaci_linka.jpg
copy /y _vzor.jpg eroze-eroze_sesuv.jpg
copy /y _vzor.jpg vodni_prvky-skalni_stupen.jpg
copy /y _vzor.jpg vodni_prvky-skalni_usek_koryta.jpg
copy /y _vzor.jpg ostatni-skladka_stara_zatez.jpg
copy /y _vzor.jpg vodni_prvky-soutok.jpg
copy /y _vzor.jpg vodni_prvky-spadovy_stupen.jpg
copy /y _vzor.jpg ostatni-strom.jpg
copy /y _vzor.jpg ostatni-strz.jpg
copy /y _vzor.jpg vodni_prvky-svejl.jpg
copy /y _vzor.jpg odvodneni-sachta.jpg
copy /y _vzor.jpg odvodneni-sachta_zasypana.jpg
copy /y _vzor.jpg vodni_prvky-tok_domapovany.jpg
copy /y _vzor.jpg odvodneni-tok_upraveny_otevreny_kanalizovany.jpg
copy /y _vzor.jpg odvodneni-tok_zatrubneny.jpg
copy /y _vzor.jpg odvodneni-trubka_odtok_ze_sachty.jpg
copy /y _vzor.jpg odvodneni-trubka_poskozena.jpg
copy /y _vzor.jpg odvodneni-trubka_pritok_do_sachty.jpg
copy /y _vzor.jpg vodni_prvky-tun.jpg
copy /y _vzor.jpg vodni_prvky-vedlejsi_koryto.jpg
copy /y _vzor.jpg eroze-eroze_vyplavovy_kuzel.jpg
copy /y _vzor.jpg odvodneni-trubka_vyust_odvodneni.jpg
copy /y _vzor.jpg vodni_prvky-vyvraty_v_koryte.jpg
copy /y _vzor.jpg vodni_prvky-zamokrena_plocha.jpg
copy /y _vzor.jpg ostatni-zed.jpg
copy /y _vzor.jpg vodni-prvky-prah_toku.jpg
copy /y _vzor.jpg vodni-prvky-akumulace_sedimentu.jpg
copy /y _vzor.jpg vodni-prvky-pramen.jpg
copy /y _vzor.jpg vodni-prvky-balvanity_skluz.jpg
